# Generated by Django 2.2 on 2019-06-06 20:34

from django.db import migrations, models
import eventex.subscriptions.tests.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20190604_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cpf',
            field=models.CharField(max_length=11, validators=[eventex.subscriptions.tests.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
    ]
