# Generated by Django 2.2.2 on 2019-06-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_courseold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['start'], 'verbose_name': 'Palestra', 'verbose_name_plural': 'Palestras'},
        ),
    ]
